<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body></body>
  <script>
    function _Promise(executor) {
      // ...
      var self = this

      self.status = 'pending'
      self.onResolvedCallback = []
      self.onRejectedCallback = []

      function resolve(value) {
        setTimeout(function () {
          // 异步执行所有的回调函数
          if (self.status === 'pending') {
            self.status = 'resolved'
            self.data = value
            for (var i = 0; i < self.onResolvedCallback.length; i++) {
              self.onResolvedCallback[i](value)
            }
          }
        })
      }

      function reject(reason) {
        setTimeout(function () {
          // 异步执行所有的回调函数
          if (self.status === 'pending') {
            self.status = 'rejected'
            self.data = reason
            for (var i = 0; i < self.onRejectedCallback.length; i++) {
              self.onRejectedCallback[i](reason)
            }
          }
        })
      }

      executor(resolve, reject)
      // ...
    }

    _Promise.prototype.then = function (onResolved, onRejected) {
      var self = this
      var _Promise2

      // 根据标准，如果then的参数不是function，则我们需要忽略它，此处以如下方式处理
      onResolved =
        typeof onResolved === 'function'
          ? onResolved
          : function (value) {
              return value
            }
      onRejected =
        typeof onRejected === 'function'
          ? onRejected
          : function (reason) {
              return reason
            }

      if (self.status === 'resolved') {
        // 如果_Promise1(此处即为this/self)的状态已经确定并且是resolved，我们调用onResolved
        // 因为考虑到有可能throw，所以我们将其包在try/catch块里
        return (_Promise2 = new _Promise(function (resolve, reject) {
          try {
            var x = onResolved(self.data)
            if (x instanceof _Promise) {
              // 如果onResolved的返回值是一个_Promise对象，直接取它的结果做为_Promise2的结果
              x.then(resolve, reject)
            }
            resolve(x) // 否则，以它的返回值做为_Promise2的结果
          } catch (e) {
            reject(e) // 如果出错，以捕获到的错误做为_Promise2的结果
          }
        }))
      }

      // 此处与前一个if块的逻辑几乎相同，区别在于所调用的是onRejected函数，就不再做过多解释
      if (self.status === 'rejected') {
        return (_Promise2 = new _Promise(function (resolve, reject) {
          try {
            var x = onRejected(self.data)
            if (x instanceof _Promise) {
              x.then(resolve, reject)
            }
          } catch (e) {
            reject(e)
          }
        }))
      }

      if (self.status === 'pending') {
        // 如果当前的_Promise还处于pending状态，我们并不能确定调用onResolved还是onRejected，
        // 只能等到_Promise的状态确定后，才能确实如何处理。
        // 所以我们需要把我们的**两种情况**的处理逻辑做为callback放入_Promise1(此处即this/self)的回调数组里
        // 逻辑本身跟第一个if块内的几乎一致，此处不做过多解释
        return (_Promise2 = new _Promise(function (resolve, reject) {
          self.onResolvedCallback.push(function (value) {
            try {
              var x = onResolved(self.data)
              if (x instanceof _Promise) {
                x.then(resolve, reject)
              }
              resolve(x)
            } catch (e) {
              reject(e)
            }
          })

          self.onRejectedCallback.push(function (reason) {
            try {
              var x = onRejected(self.data)
              if (x instanceof _Promise) {
                x.then(resolve, reject)
              }
              console.log(x)
              reject(x)
            } catch (e) {
              reject(e)
            }
          })
        }))
      }
    }
    // 为了下文方便，我们顺便实现一个catch方法
    _Promise.prototype.catch = function (onRejected) {
      return this.then(null, onRejected)
    }
  </script>
  <script>
    new _Promise(function (resolve) {
      resolve(42)
    }).then(function (value) {
      alert(value)
    })
  </script>
</html>
